=== folio-org/mod-feesfines/ramls/lost-item-fee-policy.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "CRUD lost item fee policy schema",
  "description": "CRUD to lost item fee policies",
  "type": "object",
  "properties": {
    "name": {
      "description": "Lost item fee policy name, is a required field",
      "type": "string",
      "x-fqm-visible-by-default": true,
      "x-fqm-essential": true
    },
    "description": {
      "description": "Lost item fee policy description",
      "type": "string",
      "x-fqm-visible-by-default": true
    },
    "itemAgedLostOverdue": {
      "description": "Items aged to lost after overdue entered, must be 0 or > 0 and, if > 0 must have interval selected",
      "type": "object",
      "$ref": "period.json"
    },
    "patronBilledAfterAgedLost": {
      "description": "Patron billed after aged to lost entered, must be 0 or > 0 and, if > 0 must have interval selected",
      "type": "object",
      "$ref": "period.json"
    },
    "recalledItemAgedLostOverdue": {
      "description": "Recalled items aged to lost after overdue entered, must be 0 or > 0 and, if > 0 must have interval selected",
      "type": "object",
      "$ref": "period.json"
    },
    "patronBilledAfterRecalledItemAgedLost": {
      "description": "Patron billed after a recalled item aged to lost entered, must be 0 or > 0 and, if > 0 must have interval selected",
      "type": "object",
      "$ref": "period.json"
    },
    "chargeAmountItem": {
      "description": "Option to charge amount for item",
      "type": "object",
      "$ref": "charge.json"
    },
    "lostItemProcessingFee": {
      "description": "Lost item processing fee, must be = 0 or > 0",
      "javaType": "org.folio.rest.domain.MonetaryValue",
      "type": "number",
      "x-fqm-visible-by-default": true
    },
    "chargeAmountItemPatron": {
      "description": "A flag to determine charge lost item processing fee if item declared lost by patron must be Yes or No, with default set to Yes",
      "type": "boolean"
    },
    "chargeAmountItemSystem": {
      "description": "A flag to determine charge lost item processing fee if item aged to lost by system must be Yes or No, with default set to Yes",
      "type": "boolean"
    },
    "lostItemChargeFeeFine": {
      "description": "For items not charged a fee/fine, close the loan after entered, must be 0 or > 0 and, if > 0 must have interval selected",
      "type": "object",
      "$ref": "period.json"
    },
    "returnedLostItemProcessingFee": {
      "description": "A flag to determine if lost item returned, remove lost item processing fee",
      "type": "boolean"
    },
    "replacedLostItemProcessingFee": {
      "description": "A flag to determine if lost item replaced, remove lost item processing fee",
      "type": "boolean",
      "x-fqm-visible-by-default": true
    },
    "replacementProcessingFee": {
      "description": "Amount for replacement process fee",
      "javaType": "org.folio.rest.domain.MonetaryValue",
      "type": "number",
      "x-fqm-visible-by-default": true
    },
    "replacementAllowed": {
      "description": "A flag to determine replacement allowed",
      "type": "boolean"
    },
    "lostItemReturned": {
      "description": "Option to lost item returned may be Charge overdues based on returned date up to maximum (if applicable) or Remove overdue fines, with a default of _Charge overdues based on returned date up to maximum (if applicable)",
      "type": "string"
    },
    "feesFinesShallRefunded": {
      "description": "Fees/fines shall be refunded if a lost item is returned more than entered, must be 0 or > 0 and, if > 0 must have interval selected",
      "type": "object",
      "$ref": "period.json"
    },
    "metadata": {
      "description": "Metadata about creation to lost item fee policy, provided by the server",
      "type": "object",
      "$ref": "metadata.json"
    },
    "id": {
      "description": "Lost item fee policy id, UUID",
      "$ref": "raml-util/schemas/uuid.schema",
      "x-fqm-essential": true
    }
  },
  "additionalProperties": false,
  "required": [
    "name"
  ]
}

=== folio-org/mod-feesfines/reference-data/lost-item-fees-policies/lost-item-fee-policy.json
{
  "id" : "ed892c0e-52e0-4cd9-8133-c0ef07b4a709",
  "name" : "Lost item fee policy",
  "description" : "Test lost item fee policy",
  "chargeAmountItem" : {
    "chargeType" : "actualCost",
    "amount" : 0.0
  },
  "lostItemProcessingFee" : 0.0,
  "chargeAmountItemPatron" : true,
  "chargeAmountItemSystem" : true,
  "lostItemChargeFeeFine" : {
    "duration" : 2,
    "intervalId" : "Days"
  },
  "returnedLostItemProcessingFee" : true,
  "replacedLostItemProcessingFee" : true,
  "replacementProcessingFee" : 0.0,
  "replacementAllowed" : true,
  "lostItemReturned" : "Charge"
}
